Add version check

diff --git a/.github/workflows/check-package.yml b/.github/workflows/check-package.yml
--- a/.github/workflows/check-package.yml
+++ b/.github/workflows/check-package.yml
@@ -1,10 +1,8 @@
 name: R Check Package
 
 on:
-  push:
-    branches: [ main ]
   pull_request:
-    branches: [ main ]
+    branches: [ main, dev ]
 
 jobs:
   check:
@@ -14,6 +12,28 @@ jobs:
       - uses: actions/checkout@v4
       - uses: r-lib/actions/setup-r@v2
       - uses: r-lib/actions/setup-r-dependencies@v2
+      - name: Get R package version
+        id: rversion
+        run: |
+          VERSION=$(Rscript -e 'cat(as.character(packageVersion("RPipelineTest")))')
+          echo "DEBUG: VERSION from R step is '$VERSION'"
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
+      - name: Check package version
+        run: |
+          VERSION="${{ steps.rversion.outputs.version }}"
+
+          if [ "${GITHUB_REF_NAME}" = "main" ]; then
+            TAG="v${VERSION}"
+          else
+            SHORTSHA="$(git rev-parse --short "$GITHUB_SHA")"
+            TAG="v${VERSION}-${SHORTSHA}"
+          fi
+
+          if git rev-parse -q --verify "refs/tags/$TAG" >/dev/null; then
+            echo "Tag $TAG already exists; failing."
+            exit 1
+          fi
       - uses: r-lib/actions/check-r-package@v2
         with:
           error-on: '"error"'
